#!/usr/bin/env bash
######
# Copyright (c) 2019 Michael Bright and Bamboo HR LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
######


nginx &

if [[ "${DEVELOPMENT}" != '' ]]
then
    cd /usr/lib/python2.7/site-packages/rapid
    pip install -e .

    if [[ "${IS_MASTER}" != '' ]]
    then
        pip install -e .[master]
    fi
else
    if [[ ! -d /usr/lib/python2.7/site-packages/rapid ]]
    then
        pip install rapid-framework
    fi
fi

if [[ "${PYTHON_DEPENDENCIES}" != '' ]]
then
    pip install ${PYTHON_DEPENDENCIES}
fi

/usr/local/bin/uwsgi --emperor /var/www/uwsgi.ini --die-on-term --master --plugins python
