#!/usr/bin/env bash
######
# Copyright (c) 2015 Michael Bright and Bamboo HR LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
######

set -x
cd /var/www/rapidci

flask_config=${CLIENT_CONFIG:-./docker/master-nginx.conf}
uwsgi_file=${UWSGI_INI:-./docker/master-uwsgi.ini}
grains=${GRAINS}
grains_restrict=${GRAINS_RESTRICT}

if [ -f /etc/nginx/sites-enabled/default ]
then
	rm /etc/nginx/sites-enabled/default
	cp ${flask_config} /etc/nginx/sites-available/flask.conf
	ln -s /etc/nginx/sites-available/flask.conf /etc/nginx/sites-enabled/flask.conf

	pip install -r requirements.txt
fi

cat /etc/nginx/sites-available/flask.conf

rm /var/www/app/uwsgi.ini
ln -s /var/www/rapidci/${uwsgi_file} /var/www/app/uwsgi.ini

ls -al /var/www/app/
cat /var/www/app/uwsgi.ini

cp /configs/rapidci.cfg /var/www/rapidci.cfg

if [ "${grains}" != "" ]
then
  echo "${grains}" >> /var/www/rapidci.cfg
fi

if [ "${grains_restrict}" != "" ]
then
  echo "${grains_restrict}" >> /var/www/rapidci.cfg
fi

/usr/bin/supervisord -n