"""
 Copyright (c) 2015 Michael Bright and Bamboo HR LLC

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.

adding slices and names to actions

Revision ID: 24054f4c1f76
Revises: 3b543360e21f
Create Date: 2015-12-11 10:38:27.228482

"""

# revision identifiers, used by Alembic.
revision = '24054f4c1f76'
down_revision = '3b543360e21f'
branch_labels = ()
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actions', sa.Column('name', sa.String(length=100), nullable=True))
    op.add_column('actions', sa.Column('slices', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('actions', 'slices')
    op.drop_column('actions', 'name')
    ### end Alembic commands ###
