"""
Copyright (c) 2015 Michael Bright and Bamboo HR LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

assigned_to_length

Revision ID: 8d5f3b5854d0
Revises: cdb13c1069ee
Create Date: 2019-10-07 21:35:14.305937

"""

# revision identifiers, used by Alembic.
revision = '8d5f3b5854d0'
down_revision = 'cdb13c1069ee'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('action_instances', 'assigned_to',
               existing_type=mysql.VARCHAR(length=75),
               type_=sa.String(length=150),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('action_instances', 'assigned_to',
               existing_type=sa.String(length=150),
               type_=mysql.VARCHAR(length=75),
               existing_nullable=True)
    # ### end Alembic commands ###
