"""
 Copyright (c) 2015 Michael Bright and Bamboo HR LLC

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.

callback_impl

Revision ID: 9e49690a25da
Revises: 310fbafa1f3a
Create Date: 2016-02-01 11:26:22.529503

"""

# revision identifiers, used by Alembic.
revision = '9e49690a25da'
down_revision = '310fbafa1f3a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('action_instances', sa.Column('callback_required', sa.Boolean(), default=False))
    op.add_column('actions', sa.Column('callback_required', sa.Boolean(), default=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('actions', 'callback_required')
    op.drop_column('action_instances', 'callback_required')
    ### end Alembic commands ###
