"""
Add PipelineActionCondition and ActionInstanceCondition tables

Revision ID: d5c1f4b7a9e0
Revises: cf1a4a9becad
Create Date: 2025-09-24 09:58:00

"""

# revision identifiers, used by Alembic.
revision = 'd5c1f4b7a9e0'
down_revision = 'cf1a4a9becad'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'pipeline_action_conditions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('pipeline_id', sa.Integer(), nullable=False),
        sa.Column('action_id', sa.Integer(), nullable=False),
        sa.Column('status_id', sa.Integer(), nullable=False),
        sa.Column('expression', sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(['action_id'], ['actions.id'], ),
        sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], ),
        sa.ForeignKeyConstraint(['status_id'], ['statuses.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('pipeline_id', 'action_id', name='uq_pipeline_action_condition'),
        mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_pipeline_action_conditions_action_id'), 'pipeline_action_conditions', ['action_id'], unique=False)
    op.create_index(op.f('ix_pipeline_action_conditions_id'), 'pipeline_action_conditions', ['id'], unique=False)
    op.create_index(op.f('ix_pipeline_action_conditions_pipeline_id'), 'pipeline_action_conditions', ['pipeline_id'], unique=False)
    op.create_index(op.f('ix_pipeline_action_conditions_status_id'), 'pipeline_action_conditions', ['status_id'], unique=False)

    op.create_table(
        'action_instance_conditions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('action_instance_id', sa.Integer(), nullable=False),
        sa.Column('pipeline_id', sa.Integer(), nullable=False),
        sa.Column('action_id', sa.Integer(), nullable=False),
        sa.Column('status_id', sa.Integer(), nullable=False),
        sa.Column('expression', sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(['action_id'], ['actions.id'], ),
        sa.ForeignKeyConstraint(['action_instance_id'], ['action_instances.id'], ),
        sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], ),
        sa.ForeignKeyConstraint(['status_id'], ['statuses.id'], ),
        sa.PrimaryKeyConstraint('id'),
        mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_action_instance_conditions_action_id'), 'action_instance_conditions', ['action_id'], unique=False)
    op.create_index(op.f('ix_action_instance_conditions_action_instance_id'), 'action_instance_conditions', ['action_instance_id'], unique=False)
    op.create_index(op.f('ix_action_instance_conditions_id'), 'action_instance_conditions', ['id'], unique=False)
    op.create_index(op.f('ix_action_instance_conditions_pipeline_id'), 'action_instance_conditions', ['pipeline_id'], unique=False)
    op.create_index(op.f('ix_action_instance_conditions_status_id'), 'action_instance_conditions', ['status_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_action_instance_conditions_status_id'), table_name='action_instance_conditions')
    op.drop_index(op.f('ix_action_instance_conditions_pipeline_id'), table_name='action_instance_conditions')
    op.drop_index(op.f('ix_action_instance_conditions_id'), table_name='action_instance_conditions')
    op.drop_index(op.f('ix_action_instance_conditions_action_instance_id'), table_name='action_instance_conditions')
    op.drop_index(op.f('ix_action_instance_conditions_action_id'), table_name='action_instance_conditions')
    op.drop_table('action_instance_conditions')

    op.drop_index(op.f('ix_pipeline_action_conditions_status_id'), table_name='pipeline_action_conditions')
    op.drop_index(op.f('ix_pipeline_action_conditions_pipeline_id'), table_name='pipeline_action_conditions')
    op.drop_index(op.f('ix_pipeline_action_conditions_id'), table_name='pipeline_action_conditions')
    op.drop_index(op.f('ix_pipeline_action_conditions_action_id'), table_name='pipeline_action_conditions')
    op.drop_table('pipeline_action_conditions')
    # ### end Alembic commands ###
